name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - os: linux
            arch: amd64
          - os: linux
            arch: arm64
          - os: freebsd
            arch: amd64

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get Go version
        id: go-version
        run: |
          echo "version=$(cat .tool-versions | awk '{print $2}')" >> "$GITHUB_OUTPUT"

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ steps.go-version.outputs.version }}
        
      - name: Generate build files
        run: |
          GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -o photo-organizer-${{ matrix.os }}_${{ matrix.arch }} ./cmd/photo-organizer/main.go
    
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: photo-organizer-*