name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get Go version
        id: go-version
        run: |
          cat .tool-versions | awk '{print $2} >> 
          echo "version=$(cat .tool-versions | awk '{print $2}')" >> "$GITHUB_OUTPUT"

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ steps.go-version.outputs.version }}
        
      - name: Generate build files
        uses: thatisuday/go-cross-build@v1
        with:
            platforms: 'linux/amd64, linux/arm64, freebsd/amd64'
            package: 'cmd/photo-organizer/main.go'
            name: 'photo-organizer'
            compress: 'true'
            dest: 'dist'
