name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get Go version
        id: go-version
        run: |
          echo "version=$(cat .tool-versions | awk '{print $2}')" >> "$GITHUB_OUTPUT"

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ steps.go-version.outputs.version }}
        
      - name: Generate build files
        run: |
          GOOS=linux GOARCH=amd64 go build -o photo-organizer-linux-amd64 ./cmd/photo-organizer/main.go
          GOOS=linux GOARCH=arm64 go build -o photo-organizer-linux-arm64 ./cmd/photo-organizer/main.go
          GOOS=freebsd GOARCH=amd64 go build -o photo-organizer-freebsd-amd64 ./cmd/photo-organizer/main.go
      
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: photo-organizer-*